apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
spec:
  project: default
  source:
    path: argocd-vault-plugin
    repoURL: 'https://github.com/cdshowalter/argocd-vault-plugin.git'
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
